version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0,2,4,6 * * 2"
    open-pull-requests-limit: 1
    cooldown:
      semver-patch-days: 5
      semver-minor-days: 7
      semver-major-days: 14
    groups:
      non-major-updates:
        update-types:
          - "patch"
          - "minor"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0,2,4,6 * * 2"
    open-pull-requests-limit: 1
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
