version: "2"
linters:
  enable:
    - errname
    - errorlint
    - exhaustruct
    - goconst
    - nilerr
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - usestdlibvars
    - wastedassign
  settings:
    exhaustruct:
      include:
        - 'github.com/dhth/omm/internal/ui/theme\.Theme'
        - 'github.com/dhth/omm/internal/ui\.styles'
  exclusions:
    rules:
      - linters:
          - goconst
        path: ^internal/ui/theme/
      - linters:
          - goconst
        path: _test\.go$
      - linters:
          - revive
        text: "var-naming"
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
