linters:
  enable:
    - errcheck
    - errname
    - errorlint
    - goconst
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - nilerr
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - unused
    - wastedassign
