name: back-compat

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  GO_VERSION: '1.22.5'

jobs:
  check-back-compat:
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: build head
      run: |
        go build -o omm_head
        cp omm_head /var/tmp
        rm omm_head
    - run: git checkout HEAD~1
    - name: build main
      run: |
        go build -o omm_prev
        cp omm_prev /var/tmp
    - name: Run last version
      run: |
        /var/tmp/omm_prev --db-path=/var/tmp/throwaway.db 'test: a task from previous commit'
    - name: Run current version
      run: |
        /var/tmp/omm_head --db-path=/var/tmp/throwaway.db 'test: a task from main HEAD'
        /var/tmp/omm_head --db-path=/var/tmp/throwaway.db tasks
