name: back-compat PR

on:
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/*.yml"

permissions:
  contents: read

env:
  GO_VERSION: '1.22.5'

jobs:
  check-back-compat:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: build head
      run: |
        go build -o omm_head
        cp omm_head /var/tmp
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: build main
      run: |
        go build -o omm_main
        cp omm_main /var/tmp
    - name: Run last version
      run: |
        /var/tmp/omm_main --db-path=omm-test.db 'test: a task from main'
    - name: Run current version
      run: |
        /var/tmp/omm_head --db-path=omm-test.db 'test: a task from PR HEAD'
        /var/tmp/omm_head --db-path=omm-test.db tasks
