name: back-compat PR

on:
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/*.yml"

permissions:
  contents: read

env:
  GO_VERSION: '1.23.0'

jobs:
  check-back-compat:
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: build main
      run: |
        go build -o omm_main
        cp omm_main /var/tmp
        rm omm_main
    - uses: actions/checkout@v4
    - name: build head
      run: |
        go build -o omm_head
        cp omm_head /var/tmp
        rm omm_head
    - name: Run last version
      run: |
        /var/tmp/omm_main --db-path=/var/tmp/throwaway.db 'test: a task from main'
    - name: Run current version
      run: |
        /var/tmp/omm_head --db-path=/var/tmp/throwaway.db 'test: a task from PR HEAD'
        /var/tmp/omm_head --db-path=/var/tmp/throwaway.db tasks
        ./.github/scripts/checknumtasks.sh "$(/var/tmp/omm_head --db-path=/var/tmp/throwaway.db tasks | wc -l | xargs)" 2
