name: release-check

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: go goreleaser
      - name: Release check
        run: mise run release:check
