name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: go goreleaser cosign
      - name: Release binaries
        run: mise run release
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAT}}
