name: vulncheck

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 2,6'

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: go go:golang.org/x/vuln/cmd/govulncheck
      - name: Vulnerability check
        run: mise run vulncheck
